version: '3.8'

services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-migrations
    command: bun run db:migrate
    environment:
      - DATABASE_URL=postgres://postgres:yamisukehiro@host.docker.internal:5432/postgres?sslmode=disable
    profiles:
      - migrations
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    environment:
      - DATABASE_URL=postgres://postgres:yamisukehiro@host.docker.internal:5432/postgres?sslmode=disable
      - NODE_ENV=${NODE_ENV:-production}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-3000}
      - API_VERSION=${API_VERSION:-v1}
      - LOGGING_ENABLED=${LOGGING_ENABLED:-true}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always 