version: '3.8'

services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-migrations
    command: bun run db:migrate
    environment:
      - DATABASE_URL=postgres://postgres:yamisukehiro@host.docker.internal:5432/postgres?sslmode=disable
    profiles:
      - migrations
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    environment:
      - DATABASE_URL=postgres://postgres:yamisukehiro@host.docker.internal:5432/postgres?sslmode=disable
      - NODE_ENV=${NODE_ENV:-production}
      - HOST=0.0.0.0
      - PORT=3001
      - API_VERSION=${API_VERSION:-v1}
      - LOGGING_ENABLED=${LOGGING_ENABLED:-true}
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 